server:
  port: 7007

spring:
  application:
    name: wb-oss-example

wb-cloud:
  oss:
    enabled: true
    type: minio
    minio:
      endpoint: http://127.0.0.1:9000
      accessKey: minioadmin
      accessSecret: minioadmin
      objectPrefix: wb_cloud_