#wb-cloud:
#  knife4j:
#    enabled: true
#    title: Wb-Cloud-Alibaba接口规范
#    terms-of-service-url: http://localhost:${server.port}
#    scan-package: com.wb.knife4j.example.controller
#    description: Wb-Cloud-Alibaba接口规范
#    version: 1.0.1
#    contactUrl: www.wb.com
#    contactName: BoWang
#    contatcEmail: 169966586@qq.com
#
#
