server:
  port: 7006

spring:
  application:
    name: wb-knife4j-example

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_DISCOVERY_SERVER_ADDR:127.0.0.1:8848}
        service: ${NACOS_DISCOVERY_SERVICE:${spring.application.name}}
        group: ${NACOS_DISCOVERY_GROUP:DEFAULT_GROUP}
        port: ${NACOS_DISCOVERY_PORT:${server.port}}

wb-cloud:
  knife4j:
    enabled: true
    title: Wb Cloud Alibaba 接口规范
    terms-of-service-url: http://localhost:${server.port}
    scan-package: com.wb.knife4j.example.controller
    description: Wb Cloud Alibaba 接口规范
    version: 1.0.1
    contactUrl: www.wb.com
    contactName: BoWang
    contatcEmail: 169966586@qq.com


