server:
  port: 7006

spring:
  application:
    name: wb-office-example

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false

wb-cloud:
  office:
    enabled: true
    window-width: 900px
    window-height: 1000px
